version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nfc-tron
    ports:
      - '5432:5432'
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d